### ISSUE TITLE
Margin Value and Font Family

### ISSUE THREAD

**Issue by hend0298** [hend0298/horizontal-nav#1]
@thomasjbradley Markbot says that the margin in line 37 is supposed to have a different value and that the font family in line 14 is supposed to have a different one as well.

**Comment by thomasjbradley** [comment]
*Line 14—*

`Bevan` isn’t a `cursive` font, but a `serif` font, so it’s backup should be `serif`, like this:

```css
font-family: Bevan, serif;
```

---

*Line 37—*

The `body` should almost always have a `margin` of `0`.
